### ISSUE TITLE
Generate custom sprites ?

### ISSUE THREAD

**Issue by melkael** [Wren6991/PicoDVI#13]
Hi Luke, 

I would like to use my own sprites, could you please indicate how you generate your .h files from the png images ?

Thank you for your great work

EDIT: I tried to use packtiles but was not successful in finding the right parameters (./packtiles --single --format rgab5515 128 eben_128x128.png test.h gives a different file from the one used in the lib which does not display properly)

**Comment by melkael** [comment]
I found the problem, you need to use the dithering option.
Solution: ./packtiles -d --single --format rgab5515 128 eben_128x128.png test.h

**Comment by Wren6991** [comment]
Note if you are making these for `sprite_bounce` you will also want to add the the `--metadata` flag, which adds some extra opacity information used for faster blitting. See #7
