### ISSUE TITLE
Next, input?

### ISSUE THREAD

**Issue by mwr9uk** [Wren6991/PicoDVI#2]
This is a really cool project. Bumped into it whilst thinking about line-doubling the output of a VideoNULA fitted to a BBC micro.
To make that work, we'd need input state machines to pick up the 3 x 4bits RGB, HSYNC and VSYNC at max 640x256 pixels.

**Comment by Wren6991** [comment]
If you want to do this on the fly you want to avoid sampling the sync signals every scanline. Much better to know the sync pattern in advance (or detect it before you start encoding), build your sync/blanking DMA lists up front, and then have an SM sampling the RGB based only on PCLK and DEN on a standard DPI interface.

For context, the full resolution encode uses 95% of both cores! At some point I will do a board with one RP2040 doing DPI->DVI bridging for another RP2040.

Interfacing to weird not-quite-DPI not-quite-VGA like above is left as an exercise for the reader -- I do accept PRs :)
