### ISSUE TITLE
Why do you use only 1D-Arrays?

### ISSUE THREAD

**Issue by Sorontik** [Wren6991/PicoDVI#29]
Hey @Wren6991,
just trying to dig through the color-terminal example and understand, what's going on.

I noticed that you always use 1D-Arrays, even when representing multi-D Data (2D like the charbuf or 3D like the font or array of colorplanes)

Personally, i find this very counter-intuitive and it gives me a hard time understanding the code and so i am wondering why do you do this?

**Comment by Wren6991** [comment]
It's more intuitive to me. The memory layout is meaningful, especially when you are accessing the same data in asm and C, so it should be explicit.

There are also a lot of irregularities around multidimensional arrays in C. For example, they can't be dynamically allocated (and an array of pointers to arrays is not at all the same thing as a 2D array).

**Comment by Wren6991** [comment]
> they can't be dynamically allocated

Actually I guess VLAs are a thing.

Other point stands :)
