### ISSUE TITLE
Pico DVI broken by RP2040 changes.

### ISSUE THREAD

**Issue by paulscottrobson** [Wren6991/PicoDVI#68]
Line 187 of dvi.c should be

```
while (dma_debug_hw->ch[inst->dma_cfg[i].chan_data].dbg_tcr != inst->timing->h_active_pixels / DVI_SYMBOLS_PER_WORD)
```

**Comment by ThorstenBr** [comment]
The hardware register was renamed with the PICO SDK 2.0.0 update.
Luke has updated the project to support the new SDK:

https://github.com/Wren6991/PicoDVI/commit/ca941baf37e3f04738b8e641896d85feb3430385#diff-f99979d33726536a3a7c089a03b54e553b93ad143a5bca5b98e6c3705c8225ad

=> Issue is done (but now you can no longer use old SDKs).

**Comment by Wren6991** [comment]
Thanks! Yes this should be fixed by the latest update
