### ISSUE TITLE
Question: packtiles option for sprite_bounce

### ISSUE THREAD

**Issue by kazueda** [Wren6991/PicoDVI#7]
Hello to everyone.
Please tell me packtiles options to make header files for sprite_bounce.

I tried to replace the image of sprite_bounce with my original image.
In order to prepare a header file of my original image, I use the packtiles script in /software/script directry.
But I can not watch my original image bouncing on my display.
Only moving colorful horizontal lines appear.
I tried several options like this.
$ ./packtiles -sdf rgab5515 test_128x128.png test_128x128_rgab5515.h
Of cource I edit the main.c file suitable for my original image replaceng the name of the orginal ones.

PS
I can replace the image of hello_dvi with my original image header file obtaind in use of the option shown above.

**Comment by Wren6991** [comment]
You need to pass the `--metadata` flag, or `-m`. sprite_bounce expects the opacity metadata to be present:

https://github.com/Wren6991/PicoDVI/blob/a607ff5afa9884c7d0d994c47fecddafca758e11/software/apps/sprite_bounce/main.c#L182

which makes transparent blitting much faster, especially in the common case of a single run of consecutive opaque pixels.

e.g. `./packtiles -sdmf rgab5515 test_128x128.png test_128x128_rgab5515.h`
